name: Free Fast Windows RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable Remote Desktop
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          
      - name: Create User Credentials
        run: |
          net user Admin RdpPass12345! /add
          net localgroup administrators Admin /add
          
      - name: Start Tunnel (LocalXpose)
        run: |
          Invoke-WebRequest -Uri "https://github.com/mrichards/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-pc-windows-msvc.zip" -OutFile "bore.zip"
          Expand-Archive -Path "bore.zip" -DestinationPath "."
          .\bore.exe local 3389 --to bore.pub
